feat: beagle orange
ZupIT/beagle-tests pull request #28
Opened 2022-01-27 17:31 UTC by Tiagoperes

# Description
This pull request brings all the work from the team `Orange - UX Services - Beagle Open Core` to the Beagle Open Source project.

Differently than most other projects, the Orange version of this was not a fork, which made this merge very hard. I tried to rebase it and to cherry pick the commits, nothing worked, there always was something missing at the end. To make sure everything from Beagle-Orange was coming, I chose the "nuclear" option, I copied the changes manually.

This is a single commit made by myself, but i'm only responsible for the merge. The actual author of this code is: @igorgiumellizup.

I checked it, everything but the following files are exactly the same as the version in the Orange repo:
- .gitmodules

Tasks for merging this into the main branch:
- [x] Merge the main into this (cherry picking the relevant commits)
- [ ] Verify if this is working properly (@igorgiumellizup)
- [ ] Accept each one of the PRs at the next session, with the exception of "Docs".

# Related PRs
- [Web Core](https://github.com/ZupIT/beagle-web-core/pull/380)
- [React](https://github.com/ZupIT/beagle-web-react/pull/248)
- [Angular](https://github.com/ZupIT/beagle-web-angular/pull/317)
- [Flutter](https://github.com/ZupIT/beagle-flutter/pull/44)
- [Android](https://github.com/ZupIT/beagle-android/pull/70)
- [iOS](https://github.com/ZupIT/beagle-ios/pull/301)
- [Backend Kotlin](https://github.com/ZupIT/beagle-backend-kotlin/pull/62)
- [Docs](https://github.com/ZupIT/beagle-docs/pull/837)

2022-01-27 17:52 UTC, igorgiumellizup commented
OK

2022-01-27 17:52 UTC, igorgiumellizup approved these changes

2022-01-28 19:11 UTC, igorgiumellizup requested changes
approved

2022-02-09 20:21 UTC, hernandazevedozup approved these changes

2022-02-09 20:24 UTC, arthurbleilzup approved these changes

2022-02-09 20:39 UTC, merged